### ISSUE TITLE
(extra feature) PLAYLIST: users can upvote / downvote tracks

### ISSUE THREAD

**Issue by mtamahori** [GroupMix/GroupMix#114]

**Comment by JesseBarron** [comment]
Implementation:  Write a thunk that takes the event Id, songId, and string ("UpVote","DownVote") then uses that Id to find the playlist id, for every song that matches the playlistId and SongId either add points to priority or remove points. Prioritize thunk would run, Then and socket emitter should be thrown to update everyone else's screen?
